before:
  hooks:
    - go mod tidy
builds:
  
  - id: realesrgan-scheduler-auto
    main: ./cmd/auto/
    binary: realesrgan-scheduler-auto
    ldflags:
      - -s -w -X main.build={{.Version}}
    goos:
      - freebsd
      - windows
      - darwin
      - linux
      - js

    goarch:
      - amd64
      - arm64

  - id: realesrgan-scheduler-cleanup
    main: ./cmd/cleanup/
    binary: realesrgan-scheduler-cleanup
    ldflags:
      - -s -w -X main.build={{.Version}}
    goos:
      - freebsd
      - windows
      - darwin
      - linux
      - js

    goarch:
      - amd64
      - arm64

  - id: realesrgan-scheduler-comparedirs
    main: ./cmd/comparedirs/
    binary: realesrgan-scheduler-comparedirs
    ldflags:
      - -s -w -X main.build={{.Version}}
    goos:
      - freebsd
      - windows
      - darwin
      - linux
      - js

    goarch:
      - amd64
      - arm64

  - id: realesrgan-scheduler-local
    main: ./cmd/local/
    binary: realesrgan-scheduler-local
    ldflags:
      - -s -w -X main.build={{.Version}}
    goos:
      - freebsd
      - windows
      - darwin
      - linux
      - js

    goarch:
      - amd64
      - arm64

archives:
  - id: foo
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
