before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
builds:
  - id: realesrgan-scheduler-auto
    main: ./cmd/auto/

  - id: realesrgan-scheduler-cleanup
    main: ./cmd/cleanup/

  - id: realesrgan-scheduler-comparedirs
    main: ./cmd/comparedirs/

  - id: realesrgan-scheduler-local
    main: ./cmd/local/
    
archives:
  - id: foo
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
